sudo: false
language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
notifications:
  email: false
node_js:
  - '6'
  - '4'
before_install:
  - time npm i yarn ---cache-min 99999999
install:
  - time $(npm bin)/yarn
script:
  - yarn start validate
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - yarn start report-coverage
  - yarn start release
branches:
  only:
    - master
    - next
