sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
script:
  - yarn start validate
after_success:
  - yarn global add codecov
  - codecov
  - yarn start release
branches:
  only:
    - master
    - next
